language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
compiler:
  - gcc
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3-stack
  - make -j
  - cd ./bin/
  - ./test_stack --gtest_list_tests
notifications:
  email: false
